name: 📦 Release

on:
  workflow_dispatch:
  push:
    branches: ["master"]

concurrency:
  cancel-in-progress: true
  group: release-${{ github.ref }}

defaults:
  run:
    working-directory: ./packages/web

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
