name: ⚡ Testing

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  cancel-in-progress: true
  group: testing-${{ github.ref }}

defaults:
  run:
    working-directory: ./

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build code
        env:
          NODE_ENV: production  # Set to a standard value
          SKIP_BUILD_PRODUCT_REDIRECTS: 1
        run: bun run build
      - name: Test code
        run: bun run test
